// AUTO-GENERATED BY SPECFIRST
// Source locked spec: specfirst/runs/2026-05-16T12-26-21-711Z-analyze/lockedSpec.json
// Locked spec hash: sha256:1c40d957913708ce46c52805f89eb53b1e7a6fc77ba3ecffcde5340f2537dcab
// Bob must not edit this file.

import { expect, test } from "@playwright/test";
import { AxeBuilder } from "@axe-core/playwright";

const demoRoute = "/specfirst/generated/SelectOnlyCombobox";
const scopeSelector = "[data-specfirst-root=\"SelectOnlyCombobox\"]";
const comboboxName = /Choose fruit/i;
const optionNames = ["Apple","Banana"];
const axeTags = ["wcag2a","wcag2aa","wcag21a","wcag21aa","wcag22a","wcag22aa"];

async function gotoHarness(page: import("@playwright/test").Page) {
  await page.goto(demoRoute);
}

async function combobox(page: import("@playwright/test").Page) {
  return page.getByRole("combobox", { name: comboboxName });
}

async function openWithClick(page: import("@playwright/test").Page) {
  const trigger = await combobox(page);
  await trigger.click();
  return trigger;
}

test.describe("SpecFirst contract: SelectOnlyCombobox", () => {
test("accessible-name [accessible-name]", async ({ page }) => {
  await gotoHarness(page);
  await expect(await combobox(page)).toBeVisible();
});

test("combobox-role [combobox-role]", async ({ page }) => {
  await gotoHarness(page);
  await expect(page.getByRole("combobox")).toBeVisible();
});

test("expanded-state [expanded-state]", async ({ page }) => {
  await gotoHarness(page);
  const trigger = await combobox(page);
  await expect(trigger).toHaveAttribute("aria-expanded", "false");
  await trigger.click();
  await expect(trigger).toHaveAttribute("aria-expanded", "true");
  await trigger.press("Escape");
  await expect(trigger).toHaveAttribute("aria-expanded", "false");
});

test("popup-associated [popup-associated]", async ({ page }) => {
  await gotoHarness(page);
  const trigger = await openWithClick(page);
  const controls = await trigger.getAttribute("aria-controls");
  expect(controls).toBeTruthy();
  const popup = page.locator(`[id="${controls}"]`);
  await expect(popup).toHaveAttribute("role", "listbox");
});

test("popup-listbox [popup-listbox]", async ({ page }) => {
  await gotoHarness(page);
  await openWithClick(page);
  await expect(page.getByRole("listbox")).toBeVisible();
});

test("option-roles [option-roles]", async ({ page }) => {
  await gotoHarness(page);
  await openWithClick(page);
  await expect(page.getByRole("option", { name: new RegExp(optionNames[0], "i") })).toBeVisible();
  await expect(page.getByRole("option", { name: new RegExp(optionNames[1], "i") })).toBeVisible();
});

test("selected-state [selected-state]", async ({ page }) => {
  await gotoHarness(page);
  const trigger = await openWithClick(page);
  await page.getByRole("option", { name: new RegExp(optionNames[0], "i") }).click();
  if (await page.getByRole("listbox").count() === 0) {
    await trigger.click();
  }
  await expect(page.getByRole("option", { name: new RegExp(optionNames[0], "i") })).toHaveAttribute("aria-selected", "true");
  await expect(page.getByRole("option", { name: new RegExp(optionNames[1], "i") })).toHaveAttribute("aria-selected", "false");
});

test("keyboard-arrow-down-opens [keyboard-arrow-down-opens]", async ({ page }) => {
  await gotoHarness(page);
  const trigger = await combobox(page);
  await trigger.focus();
  await trigger.press("ArrowDown");
  await expect(page.getByRole("listbox")).toBeVisible();
  const activeDescendant = await trigger.getAttribute("aria-activedescendant");
  expect(activeDescendant).toBeTruthy();
  const activeOption = page.locator(`[id="${activeDescendant}"]`);
  await expect(activeOption).toHaveAttribute("role", "option");
  await expect(activeOption).toBeVisible();
});

test("keyboard-enter-selects [keyboard-enter-selects]", async ({ page }) => {
  await gotoHarness(page);
  const trigger = await combobox(page);
  await trigger.focus();
  await trigger.press("ArrowDown");
  await expect(page.getByRole("listbox")).toBeVisible();
  await trigger.press("Enter");
  await expect(trigger).toContainText(optionNames[0]);
  await expect(trigger).toHaveAttribute("aria-expanded", "false");
});

test("keyboard-escape-closes [keyboard-escape-closes]", async ({ page }) => {
  await gotoHarness(page);
  const trigger = await openWithClick(page);
  await expect(page.getByRole("listbox")).toBeVisible();
  await trigger.press("Escape");
  await expect(trigger).toHaveAttribute("aria-expanded", "false");
  await expect(page.getByRole("listbox")).toHaveCount(0);
});

test("axe-scan [axe-scan]", async ({ page }) => {
  await gotoHarness(page);
  const collapsedResults = await new AxeBuilder({ page }).include(scopeSelector).withTags(axeTags).analyze();
  expect(collapsedResults.violations).toEqual([]);

  await openWithClick(page);
  const expandedResults = await new AxeBuilder({ page }).include(scopeSelector).withTags(axeTags).analyze();
  expect(expandedResults.violations).toEqual([]);
});
});
