import assert from "node:assert/strict";
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { generateTests } from "../../specfirst/core/test-generation/generateTests.js";
import type { LockedSpecResult, LockedSpecSuccess } from "../../specfirst/core/spec/types.js";
import type { TestGenerationGenerated, TestGenerationResult } from "../../specfirst/core/test-generation/types.js";

const repoRoot = process.cwd();
const tmpRoot = path.join(repoRoot, ".cache", "test-generation-fixtures");
const fixtureLockedSpecPath = path.join(repoRoot, "specfirst", "runs", "2026-05-16T11-59-02-720Z-analyze", "lockedSpec.json");
const fixtureComponentPath = path.join(repoRoot, "tests", "fixtures", "NamedFunctionCombobox.tsx");

fs.rmSync(tmpRoot, { recursive: true, force: true });
fs.mkdirSync(tmpRoot, { recursive: true });

const generated = testSuccessfulGeneration();
testDeterministicGeneration(generated);
testTamperedHashFailure();
testUnsupportedStrategyFailure();
testUnsupportedScopeSelectorFailure();
testSkippedAndFailedLockedSpecs();

console.log("Test generation fixture tests passed.");

function testSuccessfulGeneration(): TestGenerationGenerated {
  const project = createProject("supported");
  const result = generateTests({
    input: path.join(project.runDir, "lockedSpec.json"),
    projectRoot: project.root,
  });

  assert.equal(result.status, "generated");
  if (result.status !== "generated") {
    throw new Error("Expected generated result");
  }

  assert.equal(result.schemaVersion, "1.0.0");
  assert.equal(result.lockedSpecPath, "specfirst/runs/test-run/lockedSpec.json");
  assert.match(result.lockedSpecHash, /^sha256:[a-f0-9]{64}$/);
  assert.equal(result.testFilePath, "tests/a11y/SelectOnlyCombobox.spec.ts");
  assert.equal(result.harnessFilePath, "src/specfirst-demo/generated/SelectOnlyComboboxHarness.tsx");
  assert.equal(result.demoRoute, "/specfirst/generated/SelectOnlyCombobox");
  assert.equal(result.testCount, 11);
  assert.equal(result.nextPhase.canContinue, true);
  assert.equal(result.nextPhase.baselineTestCommand, "npx playwright test tests/a11y/SelectOnlyCombobox.spec.ts");
  assert.equal(result.nextPhase.demoRoute, "/specfirst/generated/SelectOnlyCombobox");
  assert.match(result.testFileHash, /^sha256:[a-f0-9]{64}$/);
  assert.match(result.harnessFileHash, /^sha256:[a-f0-9]{64}$/);
  assert.equal(result.generatedArtifactHashes.testFile, result.testFileHash);
  assert.equal(result.generatedArtifactHashes.harnessFile, result.harnessFileHash);
  assert.match(result.generatedArtifactHashes.combined, /^sha256:[a-f0-9]{64}$/);
  assert.deepEqual(result.generationPolicy, {
    mode: "deterministic",
    bobUsed: false,
    testsGenerated: true,
    testsRun: false,
    componentModified: false,
    lockedSpecModified: false,
    uiRendered: false,
    complianceClaimMade: false,
  });

  const expectedCheckIds = [
    "accessible-name",
    "combobox-role",
    "expanded-state",
    "popup-associated",
    "popup-listbox",
    "option-roles",
    "selected-state",
    "keyboard-arrow-down-opens",
    "keyboard-enter-selects",
    "keyboard-escape-closes",
    "axe-scan",
  ];
  assert.deepEqual(result.generatedCheckIds, expectedCheckIds);

  const testFile = readText(path.join(project.root, result.testFilePath));
  assert.ok(testFile.includes("AUTO-GENERATED BY SPECFIRST"));
  assert.ok(testFile.includes("Bob must not edit this file."));
  assert.ok(testFile.includes("Source locked spec: specfirst/runs/test-run/lockedSpec.json"));
  assert.ok(testFile.includes(`Locked spec hash: ${result.lockedSpecHash}`));
  assert.ok(testFile.includes('import { AxeBuilder } from "@axe-core/playwright";'));
  assert.ok(testFile.includes('test.describe("SpecFirst contract: SelectOnlyCombobox"'));
  assert.ok(testFile.includes('await page.goto(demoRoute);'));
  assert.ok(testFile.includes('new AxeBuilder({ page }).include(scopeSelector).withTags(axeTags).analyze()'));
  assert.ok(testFile.includes('await expect(page.getByRole("listbox")).toBeVisible();\n  await trigger.press("Enter");'));
  assert.ok(testFile.includes('await expect(page.getByRole("listbox")).toHaveCount(0);'));
  assert.ok(testFile.includes('const activeDescendant = await trigger.getAttribute("aria-activedescendant");'));
  assert.ok(testFile.includes('const activeOption = page.locator(`[id="${activeDescendant}"]`);'));
  assert.ok(testFile.includes('await expect(activeOption).toHaveAttribute("role", "option");'));
  assert.ok(testFile.includes('if (await page.getByRole("listbox").count() === 0)'));
  for (const id of expectedCheckIds) {
    assert.ok(testFile.includes(`[${id}]`), `Expected generated test title for ${id}`);
  }

  const harnessFile = readText(path.join(project.root, result.harnessFilePath));
  assert.ok(harnessFile.includes('import { SelectOnlyCombobox } from "../../../tests/fixtures/NamedFunctionCombobox.js";'));
  assert.ok(harnessFile.includes('export const routePath = "/specfirst/generated/SelectOnlyCombobox";'));
  assert.ok(harnessFile.includes('<div data-specfirst-root="SelectOnlyCombobox">'));
  assert.ok(harnessFile.includes('label="Choose fruit"'));
  assert.ok(harnessFile.includes('onChange={setValue}'));
  assert.ok(harnessFile.includes('"Apple"'));
  assert.ok(harnessFile.includes('"Banana"'));

  const resultFile = readJson<TestGenerationResult>(path.join(project.runDir, "testGenerationResult.json"));
  assert.equal(resultFile.status, "generated");

  return result;
}

function testDeterministicGeneration(first: TestGenerationGenerated): void {
  const project = createProject("deterministic");
  const firstRun = generateTests({
    input: path.join(project.runDir, "lockedSpec.json"),
    projectRoot: project.root,
  });
  const secondRun = generateTests({
    input: path.join(project.runDir, "lockedSpec.json"),
    projectRoot: project.root,
  });

  assert.equal(firstRun.status, "generated");
  assert.equal(secondRun.status, "generated");
  if (firstRun.status === "generated" && secondRun.status === "generated") {
    assert.equal(secondRun.testFileHash, firstRun.testFileHash);
    assert.equal(secondRun.harnessFileHash, firstRun.harnessFileHash);
    assert.equal(secondRun.generatedArtifactHashes.combined, firstRun.generatedArtifactHashes.combined);
    assert.equal(first.testCount, secondRun.testCount);
  }
}

function testTamperedHashFailure(): void {
  const project = createProject("tampered-hash");
  const lockedSpecPath = path.join(project.runDir, "lockedSpec.json");
  const lockedSpec = readJson<LockedSpecSuccess>(lockedSpecPath);
  lockedSpec.checks[0].description = "Tampered after lock.";
  writeJson(lockedSpecPath, lockedSpec);

  const result = generateTests({
    input: lockedSpecPath,
    projectRoot: project.root,
  });

  assertFailed(result, "locked_spec_hash_mismatch");
}

function testUnsupportedStrategyFailure(): void {
  const project = createProject("unsupported-strategy");
  const lockedSpecPath = path.join(project.runDir, "lockedSpec.json");
  const lockedSpec = readJson<LockedSpecSuccess>(lockedSpecPath);
  lockedSpec.checks[0].testStrategy = "model-written-test";
  rewriteLockedSpecHash(lockedSpec);
  writeJson(lockedSpecPath, lockedSpec);

  const result = generateTests({
    input: lockedSpecPath,
    projectRoot: project.root,
  });

  assertFailed(result, "unsupported_test_strategy");
}

function testUnsupportedScopeSelectorFailure(): void {
  const project = createProject("unsupported-scope");
  const lockedSpecPath = path.join(project.runDir, "lockedSpec.json");
  const lockedSpec = readJson<LockedSpecSuccess>(lockedSpecPath);
  lockedSpec.componentScope.selector = "#root";
  rewriteLockedSpecHash(lockedSpec);
  writeJson(lockedSpecPath, lockedSpec);

  const result = generateTests({
    input: lockedSpecPath,
    projectRoot: project.root,
  });

  assertFailed(result, "unsupported_scope_selector");
}

function testSkippedAndFailedLockedSpecs(): void {
  const skippedProject = createEmptyProject("skipped");
  const skippedSpec = {
    schemaVersion: "1.0.0",
    status: "skipped",
    component: { name: "SelectOnlyCombobox", path: "tests/fixtures/NamedFunctionCombobox.tsx" },
    reason: "manifest_load_skipped",
    message: "Skipped fixture.",
    upstream: { manifestCanContinue: false },
    nextPhase: { canContinue: false },
  };
  writeJson(path.join(skippedProject.runDir, "lockedSpec.json"), skippedSpec);
  const skipped = generateTests({
    input: path.join(skippedProject.runDir, "lockedSpec.json"),
    projectRoot: skippedProject.root,
  });
  assert.equal(skipped.status, "skipped");
  assert.equal(fs.existsSync(path.join(skippedProject.root, "tests", "a11y", "SelectOnlyCombobox.spec.ts")), false);

  const failedProject = createEmptyProject("failed");
  const failedSpec = {
    schemaVersion: "1.0.0",
    status: "failed",
    reason: "missing_checks",
    message: "Failed fixture.",
    nextPhase: { canContinue: false },
  };
  writeJson(path.join(failedProject.runDir, "lockedSpec.json"), failedSpec);
  const failed = generateTests({
    input: path.join(failedProject.runDir, "lockedSpec.json"),
    projectRoot: failedProject.root,
  });
  assertFailed(failed, "locked_spec_not_locked");
  assert.equal(fs.existsSync(path.join(failedProject.root, "tests", "a11y", "SelectOnlyCombobox.spec.ts")), false);
}

function assertFailed(result: TestGenerationResult, reason: string): void {
  assert.equal(result.status, "failed");
  if (result.status === "failed") {
    assert.equal(result.reason, reason);
    assert.equal(result.nextPhase.canContinue, false);
  }
}

function createProject(name: string): { root: string; runDir: string } {
  const project = createEmptyProject(name);
  fs.mkdirSync(path.join(project.root, "tests", "fixtures"), { recursive: true });
  fs.copyFileSync(fixtureComponentPath, path.join(project.root, "tests", "fixtures", "NamedFunctionCombobox.tsx"));
  fs.copyFileSync(fixtureLockedSpecPath, path.join(project.runDir, "lockedSpec.json"));
  return project;
}

function createEmptyProject(name: string): { root: string; runDir: string } {
  const root = path.join(tmpRoot, name);
  const runDir = path.join(root, "specfirst", "runs", "test-run");
  fs.mkdirSync(runDir, { recursive: true });
  return { root, runDir };
}

function rewriteLockedSpecHash(lockedSpec: LockedSpecSuccess): void {
  const hashInput = {
    ...lockedSpec,
    integrity: {
      ...lockedSpec.integrity,
      hash: null,
    },
  };
  lockedSpec.integrity.hash = hashCanonical(hashInput);
}

function hashCanonical(value: unknown): string {
  return `sha256:${crypto.createHash("sha256").update(JSON.stringify(canonicalize(value))).digest("hex")}`;
}

function canonicalize(value: unknown): unknown {
  if (Array.isArray(value)) {
    return value.map(canonicalize);
  }

  if (value && typeof value === "object") {
    const record = value as Record<string, unknown>;
    return Object.fromEntries(Object.keys(record).sort().map((key) => [key, canonicalize(record[key])]));
  }

  return value;
}

function readText(filePath: string): string {
  return fs.readFileSync(filePath, "utf8");
}

function readJson<T>(filePath: string): T {
  return JSON.parse(readText(filePath)) as T;
}

function writeJson(filePath: string, value: unknown): void {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, `${JSON.stringify(value, null, 2)}\n`);
}
