import type { FinalFailed, FinalPassed, FinalVerificationResult } from "./types.js";

export function generateEvidenceReport(result: FinalVerificationResult): string {
  if (result.status === "skipped" || result.status === "infra-failed" || result.status === "invalidated") {
    return `# SpecFirst Evidence Report\n\n**Status: ${result.status.toUpperCase()}**\n\n${result.message}\n`;
  }

  const r = result as FinalPassed | FinalFailed;
  const passed = r.status === "passed";
  const comp = r.checkComparison;
  const bobSession = r.bobSessionEvidence;

  const resolvedSection = comp.resolved.length > 0
    ? comp.resolved.map((id) => `- \`${id}\``).join("\n")
    : "_No checks resolved._";

  const finalFailedSection = comp.finalFailed.length > 0
    ? comp.finalFailed.map((id) => `- \`${id}\``).join("\n")
    : "_None._";

  const newFailureSection = comp.newFailures.length > 0
    ? comp.newFailures.map((id) => `- \`${id}\` (**new failure introduced**)`).join("\n")
    : "_None._";

  const manualItems = r.manualReviewRequired.length > 0
    ? r.manualReviewRequired.map((id) => `- ${id}`).join("\n")
    : "_None specified._";

  const forbiddenClaims = r.claimBoundary.forbiddenClaims
    .map((c) => `- ${c}`)
    .join("\n");

  const bobSectionStatus = bobSession.present
    ? `Present — \`${bobSession.sessionExportPath}\``
    : "**MISSING** — Bob session export not provided. Evidence is incomplete.";

  const bobResolvedSummary = comp.resolved.length > 0
    ? `Bob resolved **${comp.resolved.length}** baseline failure${comp.resolved.length > 1 ? "s" : ""} without introducing new generated-test failures.`
    : "No baseline failures were resolved by Bob.";

  const patchScope = r.bobPatch.patchScopePassed
    ? "Passed"
    : "**FAILED** — Bob edited forbidden files.";

  const changedFiles = r.bobPatch.changedFiles.length > 0
    ? r.bobPatch.changedFiles.map((f) => `- \`${f}\``).join("\n")
    : "_No files changed._";

  const finalSummary = `**${r.finalTestSummary.passed}** passed / **${r.finalTestSummary.failed}** failed / **${r.finalTestSummary.skipped}** skipped`;

  return `# SpecFirst Evidence Report

## 1. Component

- **Name:** ${r.component.name}
- **Path:** \`${r.component.path}\`
- **Pattern:** ${r.lockedSpec.path.includes("react-select-only-combobox") || r.component.name ? "react-select-only-combobox" : "unknown"}

---

## 2. Locked Contract

- **Locked spec:** \`${r.lockedSpec.path}\`
- **Hash:** \`${r.lockedSpec.hash}\`
- **Unchanged:** ${r.lockedSpec.unchanged ? "Yes" : "**NO — SPEC WAS MODIFIED**"}
- **Source model:** 7-layer rulebook
- **Created before Bob patch:** Yes

---

## 3. Generated Tests

- **Test file:** \`${r.generatedArtifacts.testFilePath}\`
- **Test file unchanged:** ${r.generatedArtifacts.testFileUnchanged ? "Yes" : "**NO**"}
- **Harness file:** \`${r.generatedArtifacts.harnessFilePath}\`
- **Harness unchanged:** ${r.generatedArtifacts.harnessFileUnchanged ? "Yes" : "**NO**"}
- **Test count:** ${r.finalTestSummary.total}

---

## 4. Baseline Result

**Status:** red-confirmed

Failed before Bob:

${comp.baselineFailed.map((id) => `- \`${id}\``).join("\n") || "_None._"}

**Meaning:** The component did not satisfy the locked automated contract before remediation.

---

## 5. IBM Bob Remediation

**Bob session:** ${bobSectionStatus}

**Changed files:**

${changedFiles}

**Patch scope:** ${patchScope}

| Artifact | Unchanged |
|----------|-----------|
| lockedSpec.json | ${r.generatedArtifacts.lockedSpecUnchanged} |
| Test file | ${r.generatedArtifacts.testFileUnchanged} |
| Harness file | ${r.generatedArtifacts.harnessFileUnchanged} |

---

## 6. Final Verification

**Status:** ${passed ? "PASSED" : "FAILED"}

**Final test result:** ${finalSummary}

**Resolved checks:**

${resolvedSection}

**Still failing checks:**

${finalFailedSection}

**New failures introduced by Bob:**

${newFailureSection}

${bobResolvedSummary}

---

## 7. Manual Review Still Required

SpecFirst does not certify WCAG conformance. Manual review is still required for:

${manualItems}

---

## 8. Claim Boundary

**Allowed conclusion:**

> Passed SpecFirst automated accessibility contract. Manual review required.

**Forbidden conclusions:**

${forbiddenClaims}

---

_Generated by SpecFirst Phase 8. Not a compliance certification._
`;
}
